[workspace]
resolver = "2"
members = ["examples/*", "crates/*", "tests/*"]

[workspace.package]
version = "0.2.0"
authors = ["Charles R Earp <charles.r.earp@gmail.com>"]
edition = "2024"
documentation = "https://docs.rs/krnl"
readme = "README.md"
homepage = "https://github.com/charles-r-earp/krnl"
repository = "https://github.com/charles-r-earp/krnl"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
krnl = { path = "crates/krnl", default-features = false }
krnlc = { path = "crates/krnlc", default-features = false }
krnl-macros = { path = "crates/krnl-macros" }
krnl-core = { path = "crates/krnl-core" }
krnl-types = { path = "crates/krnl-types", default-features = false }
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu", rev = "8ee9f2f" }
bytemuck = { version = "1.23.1", features = ["min_const_generics"] }
derive_more = { version = "2.0.1", default-features = false }
dry = "0.1.1"
paste = "1.0.15"
fxhash = "0.2.1"
half = { version = "2.6.0", default-features = false, features = [
    "num-traits",
    "bytemuck",
] }
rayon = "1.10.0"
num-traits = { version = "0.2.19", default-features = false }
itertools = "0.14.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"
#rspirv = "0.12.0"
rspirv = { git = "https://github.com/LegNeato/rspirv", branch = "localsizeid" }
