[package]
name = "compile-tests"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["rlib", "dylib"]
test = false
doctest = true
bench = false

[target.'cfg(not(target_arch = "spirv"))'.build-dependencies]
krnlc = { workspace = true, default-features = false, features = [
    "use-installed-tools",
    "rust-in",
    "bindings",
] }

[dependencies]
krnl = { workspace = true, default-features = false }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_arch, values("spirv"))',
    'cfg(krnlc)',
] }
