/* generated by krnlc 0.0.1-unstable */
    #[doc(hidden)]
    macro_rules! __krnl_cache {
        ($m:ident) => {
            __krnl::macros::__krnl_module!($m, x1f8b08000000000004ff5d4e4d0a8260101d156b9526d5a25645506e1235c81ff0089d41d40c2253,
x485b749e4ee62dda04bdf187a0f99879338ff7e61b85da300dd3b0768fbcaca2384b8596a46987e7,
xa2083d338e9c5364db89e53a9eb9ef35d24f33ebdaeb3dcf92b04acbaaf47d789bf23afafab35e8e,
xf44e2489eb21c9bc45a56dc7692412338c0138c61a4728d4fec25525198f1add2dbae48418d3a099,
x35f4ecef73827d73702bf81740ee0f7033b2061431ff866e83211004fa60938bc4483d34d81be83f,
xbedf06e9e744010000);
        };
    }