[workspace]

[package]
name = "krnlc"
version = "0.1.2-alpha"
authors = ["Charles R Earp <charles-r-earp@gmail.com>"]
edition = "2024"
description = "Kernel compiler for krnl."
documentation = "https://docs.rs/krnl"
readme = "../README.md"
homepage = "https://github.com/charles-r-earp/krnl"
repository = "https://github.com/charles-r-earp/krnl"
license = "MIT OR Apache-2.0"
publish = false
autoexamples = false
autotests = false
autobenches = false

[build-dependencies]
rustversion = "1.0.23"
vergen = { version = "10.0.3" }
vergen-gitcl = {  version = "10.0.3" }

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
clap-cargo = { version = "0.19.0", features = ["cargo_metadata"] }
anyhow = "1.0.104"
syn = { version = "3.0.6", features = ["full", "visit", "extra-traits"] }
cargo_metadata = "0.23.1"
spirv-builder = { git="https://github.com/Rust-GPU/rust-gpu", rev="e6394e08eb3356083b12f732a01906f8e49f7c4a", default-features = false }
serde = { version = "1.0.229", default-features = false, features = ["derive"] }
bincode2 = "2.0.1"
symlink = "0.1.0"
rspirv = "0.11.0"
spirv-tools = { version = "0.13.0", default-features = false }
itertools = "0.15.0"
rayon = "1.12.0"
flate2 = "1.1.10"
hex = "0.4.3"
fxhash = "0.2.1"
semver = "1.0.28"
serde_json = "1.0.151"
bytemuck = "1.25.2"
prettyplease = "0.3.0"
walkdir = "2.5.0"
zero85 = "0.2.0"

[features]
default = ["use-compiled-tools"]
use-compiled-tools = [
    "spirv-builder/use-compiled-tools",
    "spirv-tools/use-compiled-tools",
]
use-installed-tools = [
    "spirv-builder/use-installed-tools",
    "spirv-builder/use-installed-tools",
]
