[package]
name = "foo"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false


[lib]
crate-type = ["rlib", "dylib"]
test = false
doctest = false
bench = false

[target.'cfg(not(target_arch = "spirv"))'.build-dependencies]
krnlc = { workspace = true, default-features = false, features = [
    "use-installed-tools",
    "bindings",
] }

[dependencies]
krnl.workspace = true
num-traits.workspace = true

[features]
device = ["krnl/device"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_arch, values("spirv"))',
    'cfg(krnlc)',
    'cfg(foo_kernels, values("0", "1"))',
] }
