name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ matrix.timeout-minutes }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            timeout-minutes: 15
            browser: firefox
          - os: windows-latest
            timeout-minutes: 30
            browser: chrome
          - os: macos-latest
            timeout-minutes: 20
            browser: safari
    steps:
      - uses: actions/checkout@v4
      - uses: jakoch/install-vulkan-sdk-action@v1
        with:
          vulkan_version: 1.4.321.0
          cache: true
          stripdown: true
      - name: install vulkan and lavapipe
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt install -y mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers
      - name: vulkaninfo
        if: ${{ runner.os == 'Linux' }}
        run: vulkaninfo --summary
      - name: check krnl no-default-features
        run: cargo check -p krnl --no-default-features -vv
      - name: check compile tests
        # TODO forces toolchain install to fix failure when run concurrently
        run: cargo check -p compile-tests -vv
      - name: check workspace
        run: cargo check -vv
      - name: build
        run: cargo build -p krnl --all-features -vv
      - name: test
        run: cargo test --no-default-features
      - name: test device
        if: ${{ runner.os == 'Linux' }}
        run: cargo test -p integration-tests --features device -vv
      - name: install wasm-pack
        run: cargo install wasm-pack -vv
      - name: wasm test
        working-directory: tests/integration
        run: wasm-pack test --headless --${{ matrix.browser }} --no-default-features -vv
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: rustfmt
        run: cargo fmt --check
  deny:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
