name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            browser: firefox
          - os: windows-latest
            browser: chrome
          - os: macos-latest
            browser: safari
    steps:
      - uses: actions/checkout@v4
      - name: install vulkan and lavapipe
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt install -y mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers
      - name: vulkaninfo
        if: ${{ runner.os == 'Linux' }}
        run: vulkaninfo --summary
      - name: build
        run: cargo build -p krnl --all-features
      - name: test
        run: cargo test -p integration-tests
      - name: test device
        if: ${{ runner.os == 'Linux' }}
        run: cargo test -p integration-tests --features device
      - name: install wasm-pack
        run: cargo install wasm-pack -vv
      - name: wasm test
        working-directory: tests/integration
        run: wasm-pack test --headless --${{ matrix.browser }} --features run_in_browser -- -vv
  deny:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
